[tool.poetry]
name = "euphoria"
version = "0.2.1"
description = ""
authors = ["Chris Birch <datapointchris@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.0.2"
jupyter = "^1.0.0"
pandas = "^1.4.0"
pymongo = {extras = ["srv"], version = "^4.1.1"}
Markdown = "^3.3.6"
gunicorn = "^20.1.0"
Flask-SQLAlchemy = "^2.5.1"
python-dotenv = "^0.19.2"
matplotlib = "^3.5.1"
psycopg2-binary = "^2.9.3"
psycopg2 = "^2.9.3"
pynamodb = "^5.2.1"
marshmallow-sqlalchemy = "^0.28.0"
flask-marshmallow = "^0.14.0"
requests = "^2.27.1"
fastapi = "^0.79.0"
uvicorn = "^0.18.2"
docker = "^6.0.0"
Faker = "^14.1.0"
pydeps = "^1.10.22"
alembic = "^1.8.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
black = {version = "^22.1.0", allow-prereleases = true}
livereload = "^2.6.3"
jupyterthemes = "^0.20.0"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
