[tool.poetry]
name = "ichrisbirch"
version = "0.9.0"
description = ""
authors = ["Chris Birch <datapointchris@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/datapointchris/ichrisbirch"
homepage = "http://www.ichrisbirch.com"

[tool.poetry.dependencies]
python = "^3.10.1"
fastapi = "^0.79.0"
sqlalchemy = "^2.0.8"
python-dotenv = "^0.19.2"
psycopg2-binary = "^2.9.3"
psycopg2 = "^2.9.3"

[tool.poetry.scripts]


[tool.poetry.group.dev.dependencies]
pandas = "^1.4.0"
alembic = "^1.8.1"
livereload = "^2.6.3"
jupyter = "^1.0.0"
jupyterthemes = "^0.20.0"
wily = "^1.23.0"
pre-commit = "^3.0.4"
mkdocs-material = "^9.1.4"

[tool.poetry.group.cicd.dependencies]
Faker = "^14.1.0"
black = { version = "^22.1.0", allow-prereleases = true }
coverage = "^6.4.4"
docker = "^6.0.0"
flake8 = "^4.0.1"
pytest-md = "^0.2.0"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
mypy = "^1.0.0"
pytest-asyncio = "^0.20.3"
bandit = "^1.7.4"
interrogate = "^1.5.0"
isort = "^5.12.0"

[tool.poetry.group.prod.dependencies]
Flask = "^2.0.2"
pynamodb = "^5.2.1"
uvicorn = "^0.18.2"
pydeps = "^1.10.22"
requests = "^2.27.1"
colorama = "^0.4.6"
pymongo = { extras = ["srv"], version = "^4.1.1" }
Markdown = "^3.3.6"
gunicorn = "^20.1.0"
matplotlib = "^3.5.1"


[tool.black]
line-length = 120
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
line_length = 120
profile = "black"
atomic = true
skip = [".gitignore"]
extend_skip = [".md", ".json"]

[tool.bandit]
exclude_dirs = ["tests", "scripts"]
skips = ["B311"]

[tool.interrogate]
fail-under = 25
ignore-init-method = true
ignore-semiprivate = true
ignore-private = true
ignore-magic = true
ignore-module = true
ignore-nested-functions = false
ignore-init-module = false
ignore-property-decorators = false
exclude = ["alembic"]
verbose = 2
omit-covered-files = false
quiet = false
whitelist-regex = []
ignore-regex = []
color = true

[tool.pytest.ini_options]
addopts = ""
minversion = "6.0"
testpaths = ["ichrisbirch/tests"]

[tool.coverage.run]
parallel = true
branch = true
source = ["ichrisbirch"]
omit = ["ichrisbirch/alembic"]

[tool.coverage.paths]
source = ["ichrisbirch"]

[tool.coverage.report]
fail_under = 25
show_missing = true
exclude_lines = ["pragma: no cover"]

# these settings will be applied globally
[tool.refurb]
enable_all = true

# these will only be applied to the "src" folder
# [[tool.refurb.amend]]
# path = "src"
# ignore = ["FURB123", "FURB120"]

# these will only be applied to the "src/util.py" file
# [[tool.refurb.amend]]
# path = "src/util.py"
# ignore = ["FURB125", "FURB148"]

[tool.mypy]
ignore_missing_imports = true

warn_return_any = false

# [[tool.mypy.overrides]]
# module = [
#     "somelibrary",
#     "some_other_library"
# ]
# ignore_missing_imports = true

[build-system]
requires = ["poetry-core=>1.3.2"]
build-backend = "poetry.core.masonry.api"
