[tool.poetry]
name = "euphoria"
version = "0.1.0"
description = ""
authors = ["Chris Birch <datapointchris@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.0.2"
jupyter = "^1.0.0"
pandas = "^1.4.0"
pymongo = "^4.0.1"
Markdown = "^3.3.6"
gunicorn = "^20.1.0"
Flask-SQLAlchemy = "^2.5.1"
python-dotenv = "^0.19.2"
matplotlib = "^3.5.1"
psycopg2 = "^2.9.3"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
black = {version = "^22.1.0", allow-prereleases = true}
livereload = "^2.6.3"
jupyterthemes = "^0.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
