[tool.poetry]
name = "euphoria"
version = "0.5.1"
description = ""
authors = ["Chris Birch <datapointchris@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10.1"
Flask = "^2.0.2"
pandas = "^1.4.0"
pymongo = {extras = ["srv"], version = "^4.1.1"}
Markdown = "^3.3.6"
gunicorn = "^20.1.0"
python-dotenv = "^0.19.2"
matplotlib = "^3.5.1"
psycopg2-binary = "^2.9.3"
psycopg2 = "^2.9.3"
pynamodb = "^5.2.1"
requests = "^2.27.1"
fastapi = "^0.79.0"
uvicorn = "^0.18.2"
pydeps = "^1.10.22"
sqlalchemy = "^1.4.42"
Faker = "^14.1.0"

[tool.poetry.dev-dependencies]
alembic = "^1.8.1"
black = {version = "^22.1.0", allow-prereleases = true}
coverage = "^6.4.4"
docker = "^6.0.0"
flake8 = "^4.0.1"
livereload = "^2.6.3"
jupyter = "^1.0.0"
jupyterthemes = "^0.20.0"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-md = "^0.2.0"
wily = "^1.23.0"

[tool.poetry.group.dev.dependencies]
colorama = "^0.4.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
