[tool.poetry]
name = "ichrisbirch"
version = "0.9.0"
description = "Playground for making fun and silly things"
authors = ["Chris Birch <datapointchris@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/datapointchris/ichrisbirch"
homepage = "http://www.ichrisbirch.com"
documentation = "http://docs.ichrisbirch.com"


# ---------- Dependencies ---------- #


[tool.poetry.dependencies]
alembic = "^1.12.0"
colorama = "^0.4.6"
Flask = "^2.3.3"
gunicorn = "^20.1.0"
psycopg2 = "^2.9.3"
psycopg2-binary = "^2.9.3"
python = "^3.10.1"
python-dotenv = "^0.19.2"
requests = "^2.27.1"
sqlalchemy = "^2.0.20"
uvicorn = "^0.23.2"
attrs = "^23.1.0"
pendulum = "^2.1.2"
apscheduler = "^3.10.1"
strenum = "^0.4.10"
python-json-logger = "^2.0.7"
fastapi = "^0.103.1"
pydantic = "^2.4.2"

[tool.poetry.group.dev.dependencies]
deptry = "^0.10.0"
jupyter = "^1.0.0"
jupyterthemes = "^0.20.0"
livereload = "^2.6.3"
mkdocs-material = "^9.1.4"
pandas = "^1.4.0"
pre-commit = "^3.0.4"
types-requests = "^2.28.11.17"
wily = "^1.23.0"

[tool.poetry.group.cicd.dependencies]
bandit = "^1.7.4"
black = { version = "^22.1.0", allow-prereleases = true }
coverage = "^7.3.1"
docker = "^6.1.3"
Faker = "^14.1.0"
flake8 = "^6.1.0"
interrogate = "^1.5.0"
isort = "^5.12.0"
mypy = "^1.0.0"
pytest = "^7.4.1"
pytest-asyncio = "^0.20.3"
pytest-cov = "^4.1.0"
pytest-md = "^0.2.0"
pytest-playwright = "^0.3.3"
httpx = "^0.24.1"

[tool.poetry.group.prod.dependencies]
pydeps = "^1.10.22"
Markdown = "^3.3.6"


# ---------- Configurations ---------- #


[tool.bandit]
exclude_dirs = ["tests", "scripts"]
skips = ["B311"]


[tool.black]
line-length = 120
skip-string-normalization = true
exclude = '''
(
/alembic
| .git
| .mypy_cache
| .venv
| build
| dist
)
'''

[tool.codespell]
skip = '*.css.map'
ignore-words-list = "astroid,aNULL,ANULL,anull"
check-filenames = true
# count = ""
# quiet-level = 3


[tool.coverage.run]
parallel = true
branch = true
source = ["ichrisbirch"]
omit = ["ichrisbirch/alembic"]

[tool.coverage.paths]
source = ["ichrisbirch"]

[tool.coverage.report]
fail_under = 25
show_missing = true
exclude_lines = ["pragma: no cover"]


[tool.isort]
line_length = 120
profile = "black"
atomic = true
skip = [".gitignore"]
extend_skip = [".md", ".json"]


[tool.mypy]
pretty = true
ignore_missing_imports = true
# strict = true
allow_untyped_defs = true
check_untyped_defs = false  # Can enable this when all the routes are updated
plugins = ["pydantic.mypy"]
warn_return_any = false


[tool.pytest.ini_options]
addopts = ""
minversion = "6.0"
testpaths = ["tests"]


[tool.refurb]
enable_all = true


# ---------- Build System ---------- #


[build-system]
requires = ["poetry-core=>1.3.2"]
build-backend = "poetry.core.masonry.api"
