[tool.poetry]
name = "ichrisbirch"
version = "0.9.0"
description = "Playground for making fun and silly things"
authors = ["Chris Birch <datapointchris@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/datapointchris/ichrisbirch"
homepage = "http://www.ichrisbirch.com"
documentation = "http://docs.ichrisbirch.com"


# ---------- Dependencies ---------- #


[tool.poetry.dependencies]
alembic = "^1.8.1"
colorama = "^0.4.6"
fastapi = "^0.79.0"
Flask = "^2.0.2"
gunicorn = "^20.1.0"
psycopg2 = "^2.9.3"
psycopg2-binary = "^2.9.3"
python = "^3.10.1"
python-dotenv = "^0.19.2"
pydantic = "^1.10.7"
requests = "^2.27.1"
sqlalchemy = "^2.0.8"
uvicorn = "^0.18.2"
attrs = "^23.1.0"

[tool.poetry.group.dev.dependencies]
deptry = "^0.10.0"
jupyter = "^1.0.0"
jupyterthemes = "^0.20.0"
livereload = "^2.6.3"
mkdocs-material = "^9.1.4"
pandas = "^1.4.0"
pre-commit = "^3.0.4"
types-requests = "^2.28.11.17"
wily = "^1.23.0"

[tool.poetry.group.cicd.dependencies]
bandit = "^1.7.4"
black = { version = "^22.1.0", allow-prereleases = true }
coverage = "^6.4.4"
docker = "^6.0.0"
Faker = "^14.1.0"
flake8 = "^4.0.1"
interrogate = "^1.5.0"
isort = "^5.12.0"
mypy = "^1.0.0"
pytest = "^7.1.1"
pytest-asyncio = "^0.20.3"
pytest-cov = "^3.0.0"
pytest-md = "^0.2.0"

[tool.poetry.group.prod.dependencies]
# pynamodb = "^5.2.1"
pydeps = "^1.10.22"
# pymongo = { extras = ["srv"], version = "^4.1.1" }
Markdown = "^3.3.6"


# ---------- Configurations ---------- #


[tool.bandit]
exclude_dirs = ["tests", "scripts"]
skips = ["B311"]


[tool.black]
line-length = 120
skip-string-normalization = true
exclude = ["alembic", ".git", ".mypy_cache", ".venv", "build", "dist"]


[tool.coverage.run]
parallel = true
branch = true
source = ["ichrisbirch"]
omit = ["ichrisbirch/alembic"]

[tool.coverage.paths]
source = ["ichrisbirch"]

[tool.coverage.report]
fail_under = 25
show_missing = true
exclude_lines = ["pragma: no cover"]


[tool.interrogate]
fail-under = 25
ignore-init-method = true
ignore-semiprivate = true
ignore-private = true
ignore-magic = true
ignore-module = true
ignore-nested-functions = false
ignore-init-module = false
ignore-property-decorators = false
exclude = ["alembic"]
verbose = 2
omit-covered-files = false
quiet = false
whitelist-regex = []
ignore-regex = []
color = true


[tool.isort]
line_length = 120
profile = "black"
atomic = true
skip = [".gitignore"]
extend_skip = [".md", ".json"]


[tool.mypy]
ignore_missing_imports = true
plugins = ["pydantic.mypy"]
warn_return_any = false


[tool.pytest.ini_options]
addopts = ""
minversion = "6.0"
testpaths = ["ichrisbirch/tests"]


[tool.refurb]
enable_all = true


# ---------- Build System ---------- #


[build-system]
requires = ["poetry-core=>1.3.2"]
build-backend = "poetry.core.masonry.api"
