name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ["3.10", "3.11"]
        poetry-version: ["1.2.0", "1.3.2"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        poetry install --only cicd

    - name: Install black
      uses: psf/black@stable
      with:
        options: "--check --verbose --color"

    - name: Run flake8
      run: |
        flake8 .
      continue-on-error: true

    - name: Run isort
      run: |
        isort --check .

    - uses: isort/isort-action@master

    - name: Run bandit scan
      run: |
        bandit -c pyproject.toml -r .

    - name: Shellcheck
      uses: ludeeus/action-shellcheck@master

    - name: interrogate
      uses: JackMcKew/python-interrogate-check@main
      with:
        path: 'package_name'

    - name: Test with pytest
      run: |
        coverage run -m pytest discover
        coverage report -m --fail-under=25

    - name: mypy
      uses: jpetrucciani/mypy-check@master
