name: Deploy Project

on:
  workflow_run:
    workflows: [Validate Python Project]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy-project:
    name: Deploy project to EC2
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    env:
      SSH_KEY_PATH: ichrisbirch_key
      REMOTE_USER: ubuntu
      REMOTE_HOST: 18.117.41.228

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull and Re-install Project
        run: |
          echo "${{ secrets.ICHRISBIRCH_KEY }}" > $SSH_KEY_PATH && chmod 600 $SSH_KEY_PATH
          ssh -t -o StrictHostKeyChecking=no -i $SSH_KEY_PATH $REMOTE_USER@$REMOTE_HOST '
            cd /var/www/ichrisbirch &&
            git pull &&
            git secret reveal -f &&
            sudo rm -rf .venv &&
            poetry install --without dev,cicd
          '

      - name: Restart Supervisor
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_KEY_PATH $REMOTE_USER@$REMOTE_HOST 'sudo supervisorctl reload'
