name: Deploy Project

on:
  workflow_run:
    workflows: [Validate Python Project]
    types: [completed]
  workflow_dispatch:

env:
  ENVIRONMENT: "testing"

jobs:
  deploy-project:
    name: Deploy project to EC2
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull and Re-install Project
        run: |
          echo "${{ secrets.ICHRISBIRCH_KEY }}" > ichrisbirch_key && chmod 600 ichrisbirch_key
          ssh -t -o StrictHostKeyChecking=no -i ichrisbirch_key ubuntu@23.22.30.103 '
            cd /var/www/ichrisbirch &&
            git pull &&
            git secret reveal -f &&
            poetry install
          '
      - name: Restart Supervisor
        run: |
          ssh -o StrictHostKeyChecking=no -i ichrisbirch_key ubuntu@23.22.30.103 'sudo supervisorctl reload'
