name: Check for Terraform Infrastructure Changes

on:
  schedule:
    - cron: '0 0/4 * * *'  # Every 6 Hours
  workflow_dispatch:

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-${{ github.event.repository.name }}-role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ github.workspace }}/terraform

      - name: Check for Infrastructure Changes
        id: check_infra_changes
        run: python3 ../scripts/terraform_infra_check.py ${{ secrets.GMAIL_APP_PASSWORD }}
        working-directory: ${{ github.workspace }}/terraform
