name: Check for Terraform Infrastructure Changes

on:
#   schedule:
#     - cron: '0 0/2 * * *'  # Every 12 Hours
  workflow_dispatch:
  push:
    branches:
      - master

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Ubuntu Installs
        run: |
          sudo apt update
          sudo apt install git-secret gpg -y

      - name: "git-secret Reveal .env files"
        run: |
          # Import private key and avoid the "Inappropriate ioctl for device" error
          echo ${{ secrets.CICD_GPG_KEY }} | tr ',' '\n' | gpg --batch --yes --pinentry-mode loopback --import
          git secret reveal

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-${{ github.event.repository.name }}-role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Initialize Terraform
        run: terraform init

      # - name: Terraform Validate
      #   run: terraform validate

      # - name: Terraform Plan
      #   id: terraform_plan
      #   run: terraform plan -detailed-exitcode -out=tfplan
      #   continue-on-error: true

      # - name: Display Terraform Plan Exit Code
      #   run: |
      #     echo "Terraform plan exit code: ${{ steps.terraform_plan.outputs.exitcode }}"

      - name: Test Python subprocess output codes
        run: |
          import subprocess
          result = subprocess.run(['sh', '-c', 'exit 55'])
          print(f'Exit code: {result.returncode}')
        shell: python

      # - name: Check for Infrastructure Changes
      #   id: check_infra_changes
      #   run: python3 ../scripts/terraform_infra_check.py ${{ secrets.GMAIL_APP_PASSWORD }}
      #   # if: steps.terraform_plan.outputs.exitcode == 2
